### PR TITLE
com.github.hezral.clips 1.0.1

### PR DESCRIPTION
**Pull request by danrabbit**
Repository: [hezral/clips](https://github.com/hezral/clips)
Submitted By: @hezral

## Review Checklist

- [x] https://github.com/hezral/clips/issues/8
- [x] Does what it says
- [x] Matches description in AppData
- [x] Matches screenshot
- [x] AppData custom colors are contrasty
- [x] Name is unique and non-confusing
- [x] Uses elementary Flatpak runtime
- [ ] https://github.com/hezral/clips/issues/9
- [x] https://github.com/hezral/clips/issues/10

### CODE REVIEW

**Comment by cassidyjames** [comment]
This looks neat! :open_mouth:

**Comment by hezral** [comment]
I made a new release with 1.0.1 tag should a new PR be created or its continued here? 

https://github.com/hezral/clips/releases/tag/1.0.1

**Comment by danrabbit** [comment]
@hezral I can update the PR here :)

**Comment by danrabbit** [comment]
I'm a little nervous about an app that has both secrets and network access, but it seems like there's legit use happening so I think this is probably good to go

**Comment by hezral** [comment]
thank you @danrabbit!

**Pull request merged**
