### PR TITLE
com.github.hezral.inspektor.json 2.0.1

### PR DESCRIPTION
**Pull request by hezral**
Repository: [hezral/inspektor](https://github.com/hezral/inspektor)
Submitted By: @hezral 

Review Checklist
- [x]  App opens
- [x]  Does what it says

AppData
- [x]  Name is unique and non-confusing
- [x] https://github.com/hezral/inspektor/issues/38
- [x] https://github.com/hezral/inspektor/issues/39
- [x]  Matches description
- [x]  Matches screenshot
- [x]  Release tag with matching version and YYYY-MM-DD date
- [x]  Custom colors meet WCAG A contrast or greater
- [x]  OARS info matches
- [x] https://github.com/hezral/inspektor/issues/41

Flatpak
- [x]  Uses elementary runtime
- [x]  Sandbox permissions are reasonable
- [x] https://github.com/hezral/inspektor/issues/37
- [x] https://github.com/hezral/inspektor/issues/40

### CODE REVIEW

**Review by danrabbit — CHANGES_REQUESTED** [review]
It seems like a portion of this was copy/pasted from other projects and it has the same issue as other recent submissions where it can't be installed via Sideload. I've filed a few issues

**Comment by hezral** [comment]
Hey @danrabbit i've fixed the issues and release https://github.com/hezral/inspektor/releases/tag/2.0.1 thanks!

**Comment by danrabbit** [comment]
@hezral looks like this one just needs the 2.0.2 and it's ready to go as well!

**Comment by hezral** [comment]
@danrabbit fixed and released 😄 https://github.com/hezral/inspektor/releases/tag/2.0.2

**Review by danrabbit — APPROVED** [review]
Nice work, looks great!

**Review by danrabbit — APPROVED** [review]

**Comment by hezral** [comment]
thanks for the guidance!

**Pull request merged**
