### PR TITLE
Added com.github.rajsolai.textsnatcher v1.0.0

### PR DESCRIPTION
**Pull request by RajSolai**
TextSnatcher, OCR application

## Review Checklist
- [x] App opens
- [x] Does what it says
- [x] https://github.com/RajSolai/TextSnatcher/issues/3
- [x] Categories match

### AppData
- [x] Name is unique and non-confusing
- [x] Matches description
- [x] Matches screenshot
- [ ] Release tag with matching version and YYYY-MM-DD date
- [x] OARS info matches

### Flatpak
- [x] Uses elementary runtime
- [x] https://github.com/RajSolai/TextSnatcher/issues/1
- [x] https://github.com/RajSolai/TextSnatcher/issues/2
- [ ] Sandbox permissions are reasonable

### CODE REVIEW

**Review by danrabbit — CHANGES_REQUESTED** [review]
Hey thanks for your submission! I filed a few blockers as issue reports on your GitHub repo.

I have one non-blocking comment as well: there's a new release of the elementary Flatpak runtime available, so you'll want to update from `6` to `6.1` in your manifest

**Comment by RajSolai** [comment]
Thanks a lot @danrabbit :)

**Review by danrabbit — CHANGES_REQUESTED** [review]
Hey @RajSolai 

It looks like you added `"--system-talk-name=org.freedesktop.Accounts"` to your sandbox holes. Your app shouldn't need access to that, can you explain why you added it?

I'm also wondering about the network access. As far as I can tell your app shouldn't need network access either

**Comment by RajSolai** [comment]
- [--system-talk-name=org.freedesktop.Accounts](https://valadoc.org/granite/Granite.Settings.prefers_color_scheme.html) Granite Needs this permission for prefers_colors_scheme method but for elementaryOS it seems there is no need for this permission.
- Network permission was due to the template I used sorry.
I will remove the permission and commit the changes, Thank you @danrabbit

**Review by danrabbit — APPROVED** [review]
Looks good! Thanks for tightening up those permissions :)

**Pull request merged**
