### PR TITLE
com.github.bluesabre.darkbar 1.0.1

### PR DESCRIPTION
**Pull request by bluesabre**
https://github.com/bluesabre/darkbar/releases/tag/1.0.1

- AppStream: Add GNOME and elementary screenshots
- Flatpak: Add release details
- Flatpak: Force app to run via X11
- Flatpak: Reduce required permissions
- Flatpak: Switch to using sandboxed/packaged xprop
- Updated Translations: it, pl, tr

https://github.com/bluesabre/darkbar/releases/tag/1.0.0

- Appearance: Respect window controls layout
- Appearance: Support FreeDesktop dark style preference
- AppStream: Update x-appcenter-stripe
- Flatpak: Improved app identification and icon support
- Flatpak: Switch to io.elementary.Platform/Sdk 7
- Ignored Apps: Chrome/Edge PWA windows (always drawn by app)
- Ignored Apps: io.elementary.* (elementary always uses CSD)
- Ignored Apps: Zoom join windows (always unique)
- Meson: Fix shebang on meson/post_install.py
- Meson: Improve build system
- Preferences: Add new default style preference
- Wayland: Add support for XWayland windows
- X11: Avoid windows with null app_id
- X11: Reload window list if newly created window has no class name
- Updated Translations: es, fr, it, ja, lt, ms, ms@Arab, nl, pl, pt, pt_BR, pt_PT, ru, sv, zh, zh_CN

### CODE REVIEW

**Review by danrabbit — CHANGES_REQUESTED** [review]
Thanks for the update!

It looks like your appdata doesn't contain a releases tag! You should have a release tag describing your latest release so folks can know what changed when they update: https://docs.elementary.io/develop/appcenter/publishing-updates#release-descriptions

These are pretty broad permissions :grimacing: Are you sure these are all needed? Like the ones for accountsservice and settings daemon? Is there any way we can remove or scope down any of these?

I won't hold you back since it isn't currently well documented, but there is a portal for requesting autostart. See https://github.com/elementary/docs/issues/159

**Comment by bluesabre** [comment]
> Thanks for the update!
> 
> It looks like your appdata doesn't contain a releases tag! You should have a release tag describing your latest release so folks can know what changed when they update: https://docs.elementary.io/develop/appcenter/publishing-updates#release-descriptions
> 
> These are pretty broad permissions grimacing Are you sure these are all needed? Like the ones for accountsservice and settings daemon? Is there any way we can remove or scope down any of these?
> 
> I won't hold you back since it isn't currently well documented, but there is a portal for requesting autostart. See [elementary/docs#159](https://github.com/elementary/docs/issues/159)

Thanks for the review! I've got some updates coming soon with regard to documenting the releases and stripping down required permissions. I'm also looking into the background portal. Look forward to a 1.0.1 tag soon.

**Comment by danrabbit** [comment]
A releases tag is required to publish an update, so oncethat appdata is updated we can publish here :)

**Comment by bluesabre** [comment]
Thanks! I was already well on my way with the updates. The new tag, 1.0.1, reduces the required permissions quite a bit and adds the missing release tags. Please let me know if you have any other changes.

**Review by danrabbit — CHANGES_REQUESTED** [review]
Thanks for the quick turnaround again. It looks like your screenshot is still a whole desktop screenshot that includes another app. Your screenshot should be a window screenshot that only includes your app. Thanks!

**Comment by bluesabre** [comment]
> Thanks for the quick turnaround again. It looks like your screenshot is still a whole desktop screenshot that includes another app. Your screenshot should be a window screenshot that only includes your app. Thanks!

:crossed_fingers: Hopefully this commit is the one!

**Review by danrabbit — APPROVED** [review]
Looks good :tada:

**Pull request merged**
