### PR TITLE
com.github.alexkdeveloper.bmi 1.0.0

### PR DESCRIPTION
**Pull request by alexkdeveloper**
## Review Checklist

- [x] App opens
- [x] Does what it says
- [x] Categories match

### AppData
- [x] Name is unique and non-confusing
- [x] Matches description
- [x] https://github.com/alexkdeveloper/bmi/issues/1
- [x] Matches screenshot
- [x] Release tag with matching version and YYYY-MM-DD date
- [x] OARS info matches

### Flatpak
- [x] Uses elementary runtime
- [x] Sandbox permissions are reasonable

### CODE REVIEW

**Review by danrabbit — CHANGES_REQUESTED** [review]
Thanks for your submission! This largely looks good to me, I think the only requested change here is removing the background image from screenshots :)

**Comment by alexkdeveloper** [comment]
I took screenshots without a background, but workflows gives an error that the image is small. I zoomed in the image and the workflows gave some kind of error again. Only images with backgrounds passed the automatic checks.

**Comment by alexkdeveloper** [comment]
I created new screenshots and this is what workflows gives me:
―――――――――――――――――――――――――――――――――――――
stdout:
data/com.github.alexkdeveloper.bmi.appdata.xml: FAILED:
• style-invalid         : <image> has vertical padding [https://raw.githubusercontent.com/alexkdeveloper/bmi/main/data/screenshot1.png]
• style-invalid         : <image> has horizontal padding [https://raw.githubusercontent.com/alexkdeveloper/bmi/main/data/screenshot1.png]
• style-invalid         : <image> has vertical padding [https://raw.githubusercontent.com/alexkdeveloper/bmi/main/data/screenshot2.png]
• style-invalid         : <image> has horizontal padding [https://raw.githubusercontent.com/alexkdeveloper/bmi/main/data/screenshot2.png]
stderr:
Validation of files failed
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
I have already changed the dimensions and proportions several times. Nothing helps. What can be done about it?

**Comment by alexkdeveloper** [comment]
Changed the screenshots. Workflows didn't show any errors.

**Comment by danrabbit** [comment]
@alexkdeveloper I would recommend taking screenshots at 2x scaling and using "crop to content" in GIMP to make sure you're not clipping shadows. I made a couple of screenshots here for you:

Screenshot from 2021-12-14 10 56 44@2x
Screenshot from 2021-12-14 10 56 38@2x

**Comment by alexkdeveloper** [comment]
Thanks! Updated.

**Review by danrabbit — APPROVED** [review]
Lookin' good, nice work!

**Pull request merged**
