### PR TITLE
Create com.github.phase1geo.journaler.json

### PR DESCRIPTION
**Pull request by phase1geo**
Initial application submission.

Journaler is a journaling application designed for easy daily writing usage and robust review features.  It is written in GTK4 and makes use of the GtkSourceView-5 and SQLite libraries.  See the project's README.md file for more feature details.

## Review Checklist

- [x] App opens
- [x] Does what it says
- [x] Categories match

### AppData
- [x] Name is unique and non-confusing
- [x] Matches description
- [x] Matches screenshot
- [ ] Launchable tag with matching ID
- [ ] Release tag with matching version and YYYY-MM-DD date
- [x] Custom colors meet WCAG A contrast or greater
- [x] OARS info matches

### Flatpak
- [x] Uses elementary runtime
- [x] Sandbox permissions are reasonable

### CODE REVIEW

**Review by danirabbit — COMMENTED** [review]
Hey thanks for your submission!

I highly recommend added a `launchable` tag to your appdata since your app will not be able to be launched from AppCenter without it.

Also it looks like your release date is backdated to August, so your app probably won't show in the main banner or recently released view.

If you're okay with that, let me know and I'll go ahead and approve this release :)

**Comment by phase1geo** [comment]
I will get these issues fixed prior to release.

**Comment by phase1geo** [comment]
Updates have been applied (1.0.3).

**Review by danirabbit — APPROVED** [review]
Nice work! :rocket:

**Comment by phase1geo** [comment]
Thanks!

**Pull request merged**
