### PR TITLE
Create com.github.raibtoffoletto.litteris.json

### PR DESCRIPTION
**Pull request by raibtoffoletto**
This updates Litteris to work with Odin's new global color scheme preferences and necessary files to be packed as flatpak.

The `--filesystem=home:create` flag is necessary in the case the user wants to sync the database across devices, they can use a dropbox, nextcloud, or any other synchronised directory for that. The local version of the database is kept in the directory returned by `Environment.get_user_data_dir ()`.

## Review Checklist

- [x] App opens
- [x] Does what it says

### AppData
- [x] Name is unique and non-confusing
- [x] Matches description
- [x] https://github.com/raibtoffoletto/litteris/issues/20
- [x] https://github.com/raibtoffoletto/litteris/issues/22
- [x] Launchable tag with matching ID
- [x] Release tag with matching version and YYYY-MM-DD date
- [x] Custom colors meet WCAG A contrast or greater
- [x] OARS info matches

### Flatpak
- [x] Uses elementary runtime
- [x] https://github.com/raibtoffoletto/litteris/issues/21

### CODE REVIEW

**Review by danrabbit — CHANGES_REQUESTED** [review]
Filed a couple of issues with changes requested :)

**Comment by raibtoffoletto** [comment]
Hey Guys, I fixed the issues with the screenshots. So sorry for the delay, I've been quite busy lately.

**Comment by danrabbit** [comment]
Hey @raibtoffoletto it looks like we're just waiting on a new release tag in GitHub. The latest tag I see here is 0.1.7: https://github.com/raibtoffoletto/litteris/releases

**Comment by raibtoffoletto** [comment]
New Release published! I was just waiting for the green light and all issues to be solved! Thanks guys.

**Review by danrabbit — APPROVED** [review]
Looks good, thank you :rocket:

**Pull request merged**
