### PR TITLE
com.usebottles.bottles 2021.9.28

### PR DESCRIPTION
**Pull request by danirabbit**
Repository: [bottlesdevs/bottles-elementary](https://github.com/bottlesdevs/bottles-elementary)
Submitted By: @mirkobrombin

## Review Checklist

- [ ] App opens
- [ ] Does what it says

### AppData
- [ ] Name is unique and non-confusing
- [ ] Matches description
- [ ] Matches screenshot
- [ ] Launchable tag with matching ID
- [ ] Release tag with matching version and YYYY-MM-DD date
- [ ] Custom colors meet WCAG A contrast or greater
- [ ] OARS info matches

### Flatpak
- [x] Uses elementary runtime
- [ ] Sandbox permissions are reasonable

### CODE REVIEW

**Comment by davidmhewitt** [comment]
> Is the aarch64 build obligatory? Wine has an initial arm support but doesn't work in Bottles.

No, the failing aarch64 build won't block this from being published if it's approved. It just won't be published for aarch64 and will only be available on x86.

**Comment by mirkobrombin** [comment]
> > Is the aarch64 build obligatory? Wine has an initial arm support but doesn't work in Bottles.
> 
> No, the failing aarch64 build won't block this from being published if it's approved. It just won't be published for aarch64 and will only be available on x86.

Thanks for the explanation!

**Comment by mirkobrombin** [comment]
Oh this PR is very old and Bottles has undergone many new releases. I will have to update the manifesto and do new tests.

**Comment by orowith2os** [comment]
Noting here that the upstream repository has been archived.

**Pull request closed without merging**
