### PR TITLE
com.github.elfenware.badger 4.0.1

### PR DESCRIPTION
**Pull request by danrabbit**
- Repository: [elfenware/badger](https://github.com/elfenware/badger)
 - Submitted By: @dar5hak

### CODE REVIEW

**Comment by danrabbit** [comment]
@dar5hak I've installed badger here as a flatpak but I can't confirm that any notifications are being sent at all

**Comment by dar5hak** [comment]
Huh. Was working fine on my beta 2 with a clean flatpak installation, and even starting up automatically on every login.

Okay, I'll try to reproduce tomorrow.

**Comment by danrabbit** [comment]
@dar5hak Just to make sure, I installed it on a test machine with a clean RC2 and it seems to be working fine here, so it must be an issue with my other install! Sorry about that.

In that case, merging :)

**Comment by dar5hak** [comment]
Great, thanks a lot! 🙌

**Pull request merged**
