### PR TITLE
Resizer 2.2.0

### PR DESCRIPTION
**Pull request by peteruithoven**
Fixes: https://github.com/peteruithoven/resizer/issues/79

### CODE REVIEW

**Comment by peteruithoven** [comment]
```
Error: HttpError: Resource not accessible by integration
Error: Resource not accessible by integration
```
No idea... What resource?

**Review by danrabbit — APPROVED** [review]
Nice update!

Some non-blocking comments for your next version:

There's a new Flatpak platform available, so you'll want to update from `6` to `6.1` in your manifest

I'm assuming the accountsservice hole was added for the dark style, but we use the settings portal for that in Granite now so you can remove that from your manifest

Is it possible to scope down your app's permissions from `home`? It looks like you're using the native file chooser which doesn't require filesystem permissions

**Comment by peteruithoven** [comment]
Thanks for the review Danielle!

**Comment by peteruithoven** [comment]
> Is it possible to scope down your app's permissions from home? It looks like you're using the native file chooser which doesn't require filesystem permissions

The app also supports drag & drop, which does seem to require the home filesystem permission. (I tried)

**Pull request merged**
