### PR TITLE
Create io.github.leolost2605.detective.json

### PR DESCRIPTION
**Pull request by leolost2605**
FWIW once wingpanel is ported to gtk4 a lot of the stuff from this codebase can be used there in the applications menu for some additional features like proper file search :)

## Review Checklist

- [x] App opens
- [x] Does what it says
- [x] Categories match

### AppData
- [x] Name is unique and non-confusing
- [x] Matches description
- [ ] Matches screenshot
- [x] Launchable tag with matching ID
- [x] Release tag with matching version and YYYY-MM-DD date
- [ ] Custom colors meet WCAG A contrast or greater
- [x] OARS info matches

### Flatpak
- [x] Uses elementary runtime
- [ ] Sandbox permissions are reasonable

### CODE REVIEW

**Review by danirabbit — CHANGES_REQUESTED** [review]
Something is messed up in your screenshots. They should have a transparent background with a shadow but they have a black background and look unevenly cropped :grimacing: https://github.com/leolost2605/detective/blob/488ca501f7645baceb5dfd145ea3b506673878f9/data/screenshots/Main.png

This app asks for some pretty expansive sandbox permissions. I would recommend adding something to your metainfo about why these permissions are needed. As is there will be a lot of warnings on your app info page but no explanation of how these permissions are used by your app

**Comment by leolost2605** [comment]
I just saw elementary/gala#1957 so the screenshots should be fixed now :sweat_smile: 

Also I added a passage explaining why advanced permissions are required to the description.

**Review by danirabbit — CHANGES_REQUESTED** [review]
New screenshots look good!

I'm sorry I should have noticed this before, but the screenshot URLs are pointing to the github webpage of the screenshot and not the file itself. So for example:

`https://github.com/leolost2605/detective/blob/d7511080d724dd81fdb430c0bde9d7748654dec5/data/screenshots/Main.png`

should be

`https://raw.githubusercontent.com/leolost2605/detective/d7511080d724dd81fdb430c0bde9d7748654dec5/data/screenshots/Main.png`

Or you can use the tag instead of the commit hash:

`https://raw.githubusercontent.com/leolost2605/detective/1.0.1/data/screenshots/Main.png`

**Comment by leolost2605** [comment]
Oops those should be fixed as well now :)

**Review by danirabbit — APPROVED** [review]
Let's go :tada:

**Pull request merged**
