### PR TITLE
com.github.avojak.paint-spill 1.0.0

### PR DESCRIPTION
**Pull request by avojak**
New application: [Paint Spill](https://github.com/avojak/paint-spill/releases/tag/1.0.0)

## Review Checklist

- [x] App opens
- [x] Does what it says
- [x] Categories match

### AppData
- [x] Name is unique and non-confusing
- [x] Matches description
- [x] Matches screenshot
- [x] Launchable tag with matching ID
- [x] Release tag with matching version and YYYY-MM-DD date
- [x] Custom colors meet WCAG A contrast or greater
- [x] OARS info matches

### Flatpak
- [x] Uses elementary runtime
- [ ] Sandbox permissions are reasonableQA

### CODE REVIEW

**Comment by avojak** [comment]
I ran into an internal server error on the AppCenter dashboard yesterday after trying to get a Stripe token (after logging in with stripe and redirecting back to the dashboard). 

Since there's a suggested price of $1 set currently I _think_ this will have to wait to be merged until I can get a token in there.

**Comment by avojak** [comment]
I was able to get a Stripe key from the dashboard this afternoon, so I've updated with a new 1.0.1 release.

**Comment by danrabbit** [comment]
@avojak very cute! everything looks good except I'm wondering about that network sandbox hole. Is that necessary?

**Comment by avojak** [comment]
@danrabbit Nope definitely not necessary... 🤦🏼‍♂️ One of these days I'll submit something without a copy-paste mistake!

**Comment by avojak** [comment]
@danrabbit Fixed!

**Review by danrabbit — APPROVED** [review]

**Pull request merged**
