### PR TITLE
com.github.alexkdeveloper.raddiola 1.0.0

### PR DESCRIPTION
**Pull request by alexkdeveloper**
Repository: [alexkdeveloper/raddiola](https://github.com/alexkdeveloper/raddiola)
Submitted By: @alexkdeveloper

## Review Checklist

- [x] App opens
- [x] Does what it says

### AppData
- [x] Name is unique and non-confusing
- [x] Matches description
- [x] Matches screenshot
- [x] Launchable tag with matching ID
- [x] Release tag with matching version and YYYY-MM-DD date
- [x] Custom colors meet WCAG A contrast or greater
- [x] OARS info matches

### Flatpak
- [x] Uses elementary runtime
- [x] https://github.com/alexkdeveloper/raddiola/issues/4
- [x] Sandbox permissions are reasonable

### CODE REVIEW

**Comment by danrabbit** [comment]
Hey thanks for your submission! @alexkdeveloper can you explain why your app is requesting `--filesystem=home` permissions? I don't see where your app needs to read or write files to a user's home folder

**Comment by danrabbit** [comment]
Ah, I think I see it. It looks like you're trying to write to a toplevel hidden folder in the user's home folder, but instead you probably want to use [`Environment.get_user_data_dir ()`](https://valadoc.org/glib-2.0/GLib.Environment.get_user_data_dir.html) which should return a sandboxed location your app has access to

**Comment by alexkdeveloper** [comment]
Hi! Updated the json file. Added workflows. Packages are being collected!

**Comment by alexkdeveloper** [comment]
Hi! I'm still an inexperienced github user, so something may not work out right away) I have updated the data.

**Comment by alexkdeveloper** [comment]
I changed the permissions in json. Instead of filesystem=home to persist=. stations_for_radio_app.

**Comment by alexkdeveloper** [comment]
Stations are not created at startup. New ones are created through the program interface.

**Comment by alexkdeveloper** [comment]
My application works with this permission: 
--filesystem=home/. stations_for_radio_app 
Can I use it?

**Review by danrabbit — CHANGES_REQUESTED** [review]
@alexkdeveloper no problem :)

It looks like your app is still requesting full home permissions. You'll need to either use gsettings or switch to ` Environment.get_user_data_dir ()` as pointed out above

**Comment by alexkdeveloper** [comment]
Hi! I applied Environment.get_user_data_dir (). Removed the filesystem=home permission.

**Review by danrabbit — APPROVED** [review]
Thanks for making those changes. Looks good!

**Pull request merged**
