### PR TITLE
io.github.jhaygood86.mauborgne 0.0.1

### PR DESCRIPTION
**Pull request by danrabbit**
Repository: [jhaygood86/mauborgne](https://github.com/jhaygood86/mauborgne)
Submitted By: @jhaygood86

## Review Checklist

- [x] App opens
- [x] Does what it says
- [x] Matches description in AppData
- [x] Matches screenshot
- [x] AppData custom colors are contrasty
- [x] Name is unique and non-confusing
- [x] Uses elementary Flatpak runtime

### CODE REVIEW

**Comment by cassidyjames** [comment]
@jhaygood86 I can't confirm that scanning an OTP QR code adds it to the app at all; you can test the Flatpak build yourself using the build artifact: https://github.com/elementary/appcenter-reviews/suites/3555112318/artifacts/85264291

**Comment by jhaygood86** [comment]
@cassidyjames do you have the QR code you tested with handy? Feel free to email / twitter dm me if it you don't want it public

**Comment by jhaygood86** [comment]
@cassidyjames I just retested using the provided artifact here -- seems to work fine for me.

**Comment by cassidyjames** [comment]
@jhaygood86 I used https://freeotp.github.io/qrcode.html to generate something and confirmed I could add it with Bitwarden, but it's possible it's not compatible? (I also hid the overlay icon with the inspector to ensure I was getting the whole QR code). Am I misunderstanding the use for this app?

**Comment by jhaygood86** [comment]
@cassidyjames I'm not 100% sure its compatible with freeotp. It was designed for compatibility with Google Authenticator QR codes. It works with ones generated by OpenVPN and Google for sure. I just retested those 2 as well.

**Comment by btkostner** [comment]
freeotp should be using the _standard_ otp url schema as per the _Google_ docs it links to https://github.com/google/google-authenticator/wiki/Key-Uri-Format

**Review by cassidyjames — APPROVED** [review]

**Comment by jhaygood86** [comment]
> freeotp should be using the _standard_ otp url schema as per the _Google_ docs it links to https://github.com/google/google-authenticator/wiki/Key-Uri-Format

It's not the URI format: it looks like the actual QR code itself is formatted in a way that quirc (the underlying QR code library I use) doesn't understand. Reading the payload just gets gibberish (non-UTF 8 encoded text) that then fails when passing it to GUri to parse (since its not UTF 8 encoded text)

**Comment by btkostner** [comment]
ahhhhhh, my bad

**Pull request merged**
