### PR TITLE
com.github.avojak.iridium 1.3.0

### PR DESCRIPTION
**Pull request by danrabbit**
- Repository: [avojak/iridium](https://github.com/avojak/iridium)
 - Submitted By: @avojak

### CODE REVIEW

**Comment by danrabbit** [comment]
@avojak, It looks like you still need to update your flatpak manifest to use the stable version of our flatpak platform. So that should change from `daily` to `6`

**Comment by avojak** [comment]
Fixed and updated with a 1.3.1 patch release: https://github.com/avojak/iridium/releases/tag/1.3.1

**Comment by danrabbit** [comment]
Looks good and I can confirm it works as expected. Nice job!

**Comment by avojak** [comment]
Awesome! Thanks again for doing this first round!

**Comment by FabioLolix** [comment]
Hello, just a FYI, exist another Iridium program, it is a Chromium based browser

* https://iridiumbrowser.de/
* https://github.com/iridium-browser

**Pull request merged**
