### PR TITLE
com.github.alecaddd.taxi 2.0.2

### PR DESCRIPTION
**Pull request by danrabbit**
- Repository: [alecaddd/taxi](https://github.com/alecaddd/taxi)
 - Submitted By: @danrabbit

## Review Checklist

- [x] App opens
- [x] https://github.com/Alecaddd/taxi/issues/69
- [x] Does what it says
- [x] Matches description in AppData
- [x] Matches screenshot
- [x] AppData custom colors are contrasty
- [x] Name is unique and non-confusing
- [x] Uses elementary Flatpak runtime

### CODE REVIEW

**Comment by cassidyjames** [comment]
I can't actually seem to connect to a remote; there might need to be something about GVFS added to the manifest.

**Review by cassidyjames — CHANGES_REQUESTED** [review]
- https://github.com/Alecaddd/taxi/issues/69

**Comment by danrabbit** [comment]
Investigating!

**Comment by danrabbit** [comment]
@cassidyjames fixed

**Review by cassidyjames — APPROVED** [review]

**Pull request merged**
