### PR TITLE
Create com.github.malothebault.trivia

### PR DESCRIPTION
**Pull request by malothebault**
## Review Checklist
- [x] App opens
- [x] Does what it says
- [x] Categories match

### AppData
- [x] https://github.com/malothebault/trivia/issues/2
- [x] Name is unique and non-confusing
- [x] Matches description
- [x] Matches screenshot
- [x] Launchable tag with matching ID
- [x] Release tag with matching version and YYYY-MM-DD date
- [x] Custom colors meet WCAG A contrast or greater
- [x] https://github.com/malothebault/trivia/issues/3

### Flatpak
- [x] Uses elementary runtime
- [x] https://github.com/malothebault/trivia/issues/4
- [x] Sandbox permissions are reasonable

### CODE REVIEW

**Review by danrabbit — CHANGES_REQUESTED** [review]
Hey thanks for submitting your app and for your patience with review times! I've filed a few blocking issues in your issue tracker :)

**Comment by malothebault** [comment]
Thank you for your feedbacks, I tried to solved all the issues you mentioned. I hope I did it well, I'm still learning :)

**Comment by danrabbit** [comment]
Hey @malothebault code looks good to me, just waiting for the v0.1.0 release tag in GitHub :)

**Review by danrabbit — APPROVED** [review]
Apologies, not sure why I thought we were waiting on a release tag. Looks like the build wasn't running because the file wasn't named as `.json`. Fixed and built! :shipit:

**Pull request merged**
