### PR TITLE
com.github.ckruse.ColorMate 1.0.2

### PR DESCRIPTION
**Pull request by ckruse**
Repository: [ckruse/ColorMate](https://github.com/ckruse/ColorMate)
Submitted By: @ckruse

## Review Checklist

- [x] https://github.com/ckruse/ColorMate/issues/3
- [x] App opens
- [x] Does what it says

### AppData
- [x] Name is unique and non-confusing
- [x] Matches description
- [x] Matches screenshot
- [x] Launchable tag with matching ID
- [x] Release tag with matching version and YYYY-MM-DD date
- [x] https://github.com/ckruse/ColorMate/issues/2
- [x] Custom colors meet WCAG A contrast or greater
- [x] OARS info matches

### Flatpak
- [x] Uses elementary runtime
- [x] Sandbox permissions are reasonable

### CODE REVIEW

**Comment by ckruse** [comment]
Ok, I got the CI setup working. But it doesn't build because appstream validation says the image is too small:

```
• attribute-invalid     : <screenshot> width (537) too small [https://raw.githubusercontent.com/ckruse/ColorMate/main/ColorMate.png] minimum is 624px
• attribute-invalid     : <screenshot> height too small [https://raw.githubusercontent.com/ckruse/ColorMate/main/ColorMate.png] minimum is 351px
• style-invalid         : <image> has vertical padding [https://raw.githubusercontent.com/ckruse/ColorMate/main/ColorMate.png]
• style-invalid         : <image> has horizontal padding [https://raw.githubusercontent.com/ckruse/ColorMate/main/ColorMate.png]
```

What am I supposed to do here? I could create an image with multiple screenshots concatenated, but dunno, that seems pretty ugly to me. Same with the padding, it is necessary for the drop shadow?

**Comment by danrabbit** [comment]
@ckruse I thing those tests should be just a warning and not an error, but I'm getting a build failure here due to something wrong in appdata: https://github.com/elementary/appcenter-reviews/pull/115/checks?check_run_id=3546990519

We've seen issues with this before when there are zero-width-space characters

**Comment by ckruse** [comment]
Yes, I noticed it, too - it is because of the code elements. Documentation says it is allowed, but validation says parse error. I already fixed that on HEAD, but didn‘t have the time for a 1.0.2, sorry

**Comment by ckruse** [comment]
Ok, I hope now with v1.0.2 everything is fixed. Sorry for that many mistakes; it is my first Linux application ever, and also my first elementaryOS application ;-)

**Comment by danrabbit** [comment]
Everything looks good! Nice work. Thanks for submitting it to AppCenter :)

**Comment by ckruse** [comment]
Thanks for reviewing and merging!

**Pull request merged**
