### PR TITLE
com.github.hezral.keystrokes.json 1.0.2

### PR DESCRIPTION
**Pull request by hezral**
Repository: [hezral/keystrokes](https://github.com/hezral//keystrokes)
Submitted By: @hezral 

## Review Checklist

- [x] https://github.com/hezral/keystrokes/issues/1
- [x] App opens
- [x] Does what it says

### AppData
- [x] Name is unique and non-confusing
- [x] Matches description
- [x] Matches screenshot
- [x] Release tag with matching version and YYYY-MM-DD date
- [x] Custom colors meet WCAG A contrast or greater
- [x] https://github.com/hezral/keystrokes/issues/4
- [x] OARS info matches

### Flatpak
- [x] Uses elementary runtime
- [x] Sandbox permissions are reasonable
- [x] https://github.com/hezral/keystrokes/issues/3

### CODE REVIEW

**Comment by danrabbit** [comment]
@hezral I think this is also just waiting on a new release with that appdata fix

**Comment by hezral** [comment]
Hey @danrabbit, i created https://github.com/hezral/keystrokes/releases/tag/1.0.1 with updated manifest which removed the `appstream-compose = false` line that was causing the app name not being recognized

**Review by danrabbit — CHANGES_REQUESTED** [review]
Thanks for fixing that! I filed a couple more issues after reviewing further

**Comment by hezral** [comment]
Thanks for the patience! 

Released 1.0.2 with the fixes https://github.com/hezral/keystrokes/releases/tag/1.0.2

**Review by danrabbit — APPROVED** [review]
Looks good, nice work!

**Pull request merged**
