### PR TITLE
com.manexim.codecard 1.1.0

### PR DESCRIPTION
**Pull request by meisenzahl**
- Repository: [manexim/codecard](https://github.com/manexim/codecard)
- Release: [1.1.0](https://github.com/manexim/codecard/releases/tag/1.1.0)
- Submitted By: @meisenzahl
- Domain validation: https://manexim.com/

Based on an app idea by @cassidyjames 

## Review Checklist
- [x] App opens
- [x] Does what it says
- [x] Categories match

### AppData
- [x] Name is unique and non-confusing
- [x] Matches description
- [x] Matches screenshot
- [x] Release tag with matching version and YYYY-MM-DD date
- [x] Custom colors meet WCAG A contrast or greater
- [x] https://github.com/manexim/codecard/issues/9
- [x] OARS info matches

### Flatpak
- [x] Uses elementary runtime
- [x] Sandbox permissions are reasonable
- [x] https://github.com/manexim/codecard/issues/8

### CODE REVIEW

**Comment by meisenzahl** [comment]
https://developer.elementary.io/submissions tells me that

```
Project does not have a stable release
```

Would be great if you could provide me the Stripe key :)

**Comment by Antolius** [comment]
@meisenzahl I think your repo might be private, at least I can't find it anywhere under the [manexim](https://github.com/manexim) org.
(That might also explain issues with [developer submissions](https://developer.elementary.io/submissions).)

**Comment by meisenzahl** [comment]
@Antolius thank you for pointing this out. Yes, the repository was private 🙈

**Review by danrabbit — CHANGES_REQUESTED** [review]
Thanks for the submission! Filed a couple of issues with requested changes. Mainly, the screenshot portal should be used instead of requesting a sandbox hole here

**Comment by meisenzahl** [comment]
@danrabbit thank you for your feedback! All issues should be addressed.

**Review by danrabbit — APPROVED** [review]
Nice work!

**Pull request merged**
