### PR TITLE
com.github.ryonakano.reco 3.2.0

### PR DESCRIPTION
**Pull request by ryonakano**
Repository: [ryonakano/reco](https://github.com/ryonakano/reco)
Submitted By: @ryonakano

## Review Checklist
  
  - [ ] App opens
  - [ ] Does what it says
  - [ ] Categories match

  ### AppData
  - [ ] Name is unique and non-confusing
  - [ ] Matches description
  - [ ] Matches screenshot
  - [ ] Launchable tag with matching ID
  - [ ] Release tag with matching version and YYYY-MM-DD date
  - [ ] Custom colors meet WCAG A contrast or greater
  - [ ] OARS info matches
  
  ### Flatpak
  - [ ] Uses elementary runtime
  - [ ] Sandbox permissions are reasonable

### CODE REVIEW

**Review by danrabbit — CHANGES_REQUESTED** [review]
It looks like your UI changed. Don't forget to update screenshots :)

**Comment by ryonakano** [comment]
Thanks for pointing out that, I completely forgot updating them. :sweat_smile: I addressed changes.

We don't need another release for this change since the screenshots are only used in the readme and appdata and the appdata points to the screenshots in the latest main branch, right? I confirmed the screenshots of the current release available in the AppCenter already uses the updated ones:

Screenshot from 2021-12-20 08-13-07

**Comment by danrabbit** [comment]
Yeah there's no screenshot caching at the moment so no new update needed

**Comment by ryonakano** [comment]
@danrabbit I created another release finally :sweat_smile: Because I resolved the issue from "ancient" and bumped library version used in the project successfully!

**Review by danrabbit — APPROVED** [review]

**Pull request merged**
