### PR TITLE
com.github.rajsolai.response.json

### PR DESCRIPTION
**Pull request by RajSolai**
Requesting review for Response Application

## Review Checklist
- [ ] App opens
- [ ] Does what it says
- [ ] Categories match

### AppData
- [ ] Name is unique and non-confusing
- [ ] Matches description
- [ ] Matches screenshot
- [ ] Launchable tag with matching ID
- [ ] Release tag with matching version and YYYY-MM-DD date
- [ ] Custom colors meet WCAG A contrast or greater
- [ ] OARS info matches

### Flatpak
- [ ] Uses elementary runtime
- [ ] Sandbox permissions are reasonable

### CODE REVIEW

**Review by danrabbit — CHANGES_REQUESTED** [review]
Hey @RajSolai thanks for your submission! It doesn't look like the linked repository contains a flatpak manifest in either json or yml format. You'll need a Flatpak manifest so we can build your app. You can read more about this in our developer guide: https://docs.elementary.io/develop/writing-apps/our-first-app/packaging

**Comment by RajSolai** [comment]
Sorry I forgot to add the manifest, when I published the app on flathub the reviewers asked to remove the manifest as flathub needs the manifest to be added in a seperate repo ¯\_(ツ)_/¯

**Comment by danrabbit** [comment]
Hey @RajSolai I noticed it looked like you did add a flatpak manifest in your repo. Did you want to tag a new release and submit it for review?

**Comment by RajSolai** [comment]
Thanks @danrabbit , But I got approval for merge through another PR https://github.com/elementary/appcenter-reviews/pull/291, I closed this PR as I messed up with my fork of Repo. Sorry for the confusion.

**Comment by danrabbit** [comment]
Oh oops lol I even approved that. Thanks for clearing that up!

**Pull request closed without merging**
