### PR TITLE
Com.GitHub.tenderowl.frog 0.1.6

### PR DESCRIPTION
**Pull request by amka**
Update Frog to 0.1.6

### CODE REVIEW

**Comment by danrabbit** [comment]
Hey @amka is there a reason this is marked as a draft?

**Comment by amka** [comment]
@danrabbit actually, I thought if I send it as normal PR you can't update it if you need that. Not sure how it works in GH.

**Comment by danrabbit** [comment]
@amka ah there's a different setting for that when you submit. Draft indicates that it isn't ready to be reviewed yet :)

**Comment by danrabbit** [comment]
Update looks good to me, nice work!

**Comment by amka** [comment]
@danrabbit Glad to read it 😄

**Pull request merged**
