### PR TITLE
Update com.github.tenderowl.norka to 1.0.0

### PR DESCRIPTION
**Pull request by amka**
## New
<ul>
    <li> #57 You can create folders to structure your notes</li>
    <li> #57 Move documents to folders in and out</li>
    <li>Full backup for every doc in every folder</li>
    <li>Current path displayed in the header</li>
    <li>Set the language for spell-checking in the preferences window</li>
</ul>

## Fixes
<ul>
    <li>Header now properly inserted for non-Latin languages</li>
    <li>Autocompletion stops if no text is entered on list item</li>
    <li>Fix drag-n-drop import when the first event repeats for every next import</li>
</ul>

Grid with folders

New fonts and colors

### CODE REVIEW

**Review by danrabbit — CHANGES_REQUESTED** [review]
It looks like one of your screenshot URLs is returning a 404: https://raw.githubusercontent.com/tenderowl/norka/master/data/screenshots/app_screenshot_1.png

It looks like maybe this was supposed to point to https://raw.githubusercontent.com/tenderowl/norka/master/data/screenshots/norka-welcome.png

**Comment by amka** [comment]
I went to bed and suddenly realized that I forgot to update the screenshots :)

**Review by danrabbit — APPROVED** [review]
Nice thanks for fixing that and thanks for your patience with the review time here!

**Comment by amka** [comment]
Thank you for the elementary ;)

**Pull request merged**
