### PR TITLE
com.github.childishgiant.mixer 0.1.3

### PR DESCRIPTION
**Pull request by danrabbit**
- Repository: [childishgiant/mixer](https://github.com/childishgiant/mixer)
 - Submitted By: @childishgiant

### CODE REVIEW

**Comment by danrabbit** [comment]
A few notes here:
:x: description mentions elementary OS
:x: There's no release notes in the release notes
:x: AppData doesn't include screenshots
:heavy_check_mark: The app appears to do what it says
:heavy_check_mark: It has a unique icon

Issues have been filed in the upstream issue tracker

**Comment by danrabbit** [comment]
Looks good!

**Comment by ChildishGiant** [comment]
Should this be visible in the AppCenter? I currently can't see it on Odin, Hera or the website.

**Comment by ChildishGiant** [comment]
Hmm, it's not available at https://appcenter.elementary.io/com.github.childishgiant.mixer but it is on the appcenter now, just without screenshots
image

**Pull request merged**
