### PR TITLE
hr.from.josipantolis.starfish 1.2.0

### PR DESCRIPTION
**Pull request by Antolius**
Repository: [starfish-app/Starfish](https://github.com/starfish-app/Starfish)
Submitted By: @Antolius

## Review Checklist

- [x] App opens
- [x] Does what it says
- [x] Categories match

### AppData
- [x] Name is unique and non-confusing
- [x] Matches description
- [x] Matches screenshot
- [x] Release tag with matching version and YYYY-MM-DD date
- [x] Custom colors meet WCAG A contrast or greater
- [x] OARS info matches

### Flatpak
- [x] Uses elementary runtime
- [x] Sandbox permissions are reasonable

### CODE REVIEW

**Comment by Antolius** [comment]
I'm sorry about rudely opening this pull request without any comment. I think that's what [broke the setup action](https://github.com/elementary/appcenter-reviews/pull/152/checks?check_run_id=3808616246). I hope this helps:
https://github.com/elementary/action-appcenter-review-checklist/pull/1

**Comment by Antolius** [comment]
> I can't seem to verify that you are the owner of the website https://from.hr so it appears that the RDNN your app is using is not valid. I would recommend using `com.github.starfish_app.starfish` since that's a verifiable URL that you have write permission for

The domain is actually `josipantolis.from.hr`, I use it to host a Gemini site at gemini://josipantolis.from.hr. You can check it using Starfish or some other Gemini clients. Or, if you'd prefer, I could put up an HTTP server and host something on port 80.

If it's not a problem for you I'd prefer to keep using my own domain as opposed to the Github based one. I'm OK with hosting my code on Github today and I realize that  the AppCenter's publishing flow is tied to Github right now. But they might change their terms and conditions in the future in a way that I'm not comfortable with. Or, since I'm not paying for it, they might just limit the number of free repositories or something like that. So I'd like to keep my code and app ids decoupled from it. That way I can easily move to Gilab or to some self hosted solution in the future, transparently to users who have the app installed already.

> The filesystem permissions requested here are extremely broad, especially since this is an app that connects to the network. As it appears your app's primary purpose isn't to be a file browser, I would recommend using the file chooser portal if your app needs access to local files.

Gemini protocol, in addition to network communication, defines its own MIME type text/gemini (similar to how HTML is the most popular file type for HTTP). Installing Starfish should [add the MIME type definition](https://github.com/starfish-app/Starfish/blob/main/data/gemini-mime-type.xml) to user's system. I register Starfish as the default viewer for gemtext files.

Use-cases I would like to support are:

1. When user double-clicks a gemtext file in the Files app it opens in Starfish (opening the app if it's not running already, or bringing already running instance into focus and opening the file in the new tab).
2. When user enters a `file://...` URI pointing to a local gemtext file into Starfish's address bar the app should render the file.
3. If local gemtext file has any relative links to other local files, user should be able to navigate those. (You can see this flow in action if you open the _Introduction to Gemini_ documentation inside the Starfish app itself. It's set as the homepage upon first installing the app, and there's a menu item linking to it so that you can find it even after you've changed your homepage.)

With these features I want to match the behavior of web browsers that users are already accustomed to. While the Gemini protocol has traditionally attracted more tech savvy audience, my goal with Starfish is to make it approachable to regular users. That's why I'm trying to live up to their existing expectations of what the browser is as best as I can.

I haven't found a way to make these three use-cases work with more restrictive flatpak permissions. I only support rendering gemtext pages, so I limited Starfish to read access only. If I can configure flatpak to grant me access only to files of the gemtext MIME type that would be ideal, but I don't think that's supported (correct me if I'm wrong). This is my first flatpak (or desktop in general) app so I could be missing some obvious solution here.

**Comment by Antolius** [comment]
Hi! I've just released a new version (1.1.0) of the Starfish app. Since this review is still ongoing I've just updated the code change to link to the latest release commit in Starfish's git repository. I hope that's OK, I can open a separate pull request if you'd prefer.

I've also [limited the filesystem permission request](https://github.com/starfish-app/Starfish/commit/3e21dbc37c2016feb1a4cc9bbde0b4a88df7aadb) to only include `home:ro`. This should not limit the usability of the app too much, as most of the gemtext files that users might wish to open are probably somewhere in their home folder anyway.

**Comment by Antolius** [comment]
Hi @danrabbit I apologize for the @-mention, I hope I'm not intruding on your time too much. I feel a bit lost in the review process and don't know how to proceed with it.

I've released a new version of Starfish app today, so I updated this PR to link to the latest release commit. I've also set up an HTTP site over at the josipantolis.from.hr domain. I hope that helps solve the RDNN issue.

I can only imagine how time consuming it is to maintain a Linux distro, a desktop environment and an app platform. Plus all the extra stuff like running a company and working productively with upstream communities. I really appreciate all that work. I can understand if your time is focused elsewhere at the moment. Just please do let me know if there's anything I can do from my end to help you with this particular review.

**Comment by danrabbit** [comment]
Hey @Antolius massive apologies for dropping the ball here! I really appreciate you following up.

I appreciate you dropping filesystem permissions down to `home`. I think ideally we'd still want to push to restrict this further somehow, but that's probably okay for now

I'm not sure that having a subdomain like this meets the criteria that would ensure the RDNN is unique. Theoretically someone could buy `https://from.hr` and then host an app at `https://from.hr/josipantolis` and that would be the actual match for the RDNN scheme we're using. This is probably unlikely, but I think that's the URL you'd need to demonstrate ownership for. I'm also unable to reach `https://josipantolis.from.hr` in any case. So I think the best path here is still to use `com.github` as your RDNN prefix unless you'd like to purchase `https://from.hr` or another domain that can be verified.

**Comment by Antolius** [comment]
Tnx for the reply!

> I'm not sure that having a subdomain like this meets the criteria that would ensure the RDNN is unique. Theoretically someone could buy `https://from.hr` and then host an app at `https://from.hr/josipantolis` and that would be the actual match for the RDNN scheme we're using.

The `from.hr` 2nd level domain is defined by my country's domain name registry: CARNet. That's the same organization that manages the top level `hr` domain.  Domains under `from.hr` are intended for use by private citizens, each of who gets one free `<name>.from.hr` domain. You can think of it as similar to how `co.uk` or `gov.uk` are used in UK. I think this usage of 2nd level domains defined by the country's registry is more popular in Europe than stateside. If you want to know more about `from.hr` in prticular you can check this FAQ section: https://www.domene.hr/en/portal/faq#accordion4

> I'm also unable to reach `https://josipantolis.from.hr` in any case.

I only set up an HTTP server, as generating an SSL certificate for this self-hosted, temporary site seemed like an overkill.

**Comment by danrabbit** [comment]
Hey @Antolius this site should be online for as long as your app is published in AppCenter. Temporarily hosting a page wouldn't fulfill the purposes of making sure RDNN's are unique

**Comment by Antolius** [comment]
> Hey @Antolius this site should be online for as long as your app is published in AppCenter. Temporarily hosting a page wouldn't fulfill the purposes of making sure RDNN's are unique

I did not realize this! Ok, now I understand the need for a certificate that you pointed out. I will leave the site up indefinitely, and I'll make sure to:

* Set up a let's encrypt certificate to make it more legitimate.
* Update the site's content, as currently it's serving a sort of landing page for the Starfish app and this may not make sense once I publish other apps under the same domain.

In case you'd like to see these changes up before proceeding with this review I'll update you on my progress here. In case the current http site is enough for publishing at this point please feel free to merge the PR!

And thank you for leading me through this process. It's my first app, so it's important for me to "get it right". I'd like my contributions to open spurce to be powered by free and open solutions, such as the domain I'm issued by my country (I find that to be extremely cool and underutilized "government frature") and the elementary OS and it's development tools.

**Comment by Antolius** [comment]
@danrabbit the HTTPS site is up (and will remain up :wink: ), with Starfish project page now over at https://josipantolis.from.hr/starfish.html
Let's get this launch going! :rocket:

**Comment by cassidyjames** [comment]
Chiming in here after doing a bit of investigating; it appears `.from.hr` should be treated the same way we'd treat e.g. `.co.uk` TLDs, so I would be fine with a `hr.from.foo.app` RDNN, **if** we are going to begin verifying third-party domains. Which right now is a big _if_ since we have not yet set that precedent (which is why this is taking a bit longer than expected, @Antolius).

**Comment by Antolius** [comment]
Tank you for looking into the top level domain @cassidyjames !

I'm sorry for stirring up trouble with custom domain RDNN. Based on [this comment ](https://github.com/elementary/houston/issues/436#issuecomment-905690971) I presumed that using my own domain is supported by the new publishing procedure. This review has lasted for a while now, so I guess I can wait a bit longer. Just please let me know once you've reached a decision on supporting custom domains, even if it's a temporary one. For example if you decide not to support them for a few more months I'd rather change the RDNN now than postpone the launch by that much.

**Review by danrabbit — APPROVED** [review]
Based on Cassidy's comment about the RDNN scheme, I feel like we can go ahead and get this merged. Thanks for being patient while we're ironing out some of the kinks here!

**Pull request merged**
