### PR TITLE
com.github.jeysonflores.switcher 1.0.0

### PR DESCRIPTION
**Pull request by JeysonFlores**
Repository: [JeysonFlores/switcher](https://github.com/JeysonFlores/switcher)
Submitted By: @JeysonFlores

## Review Checklist

- [x] App opens
- [x] Does what it says
- [x] Categories match

## AppData

- [x] Name is unique and non-confusing
- [x] Matches description
- [x] https://github.com/JeysonFlores/switcher/issues/14
- [x] Matches screenshot
- [x] Launchable tag with matching ID
- [x] Release tag with matching version and YYYY-MM-DD date
- [x] Custom colors meet WCAG A contrast or greater
- [x] OARS info matches

## Flatpak

- [x] Uses elementary runtime
- [ ] https://github.com/JeysonFlores/switcher/issues/13
- [x] Sandbox permissions are reasonable

### CODE REVIEW

**Review by danrabbit — CHANGES_REQUESTED** [review]
Hey @JeysonFlores this is a really cool little app!

The only blocking request I have here is for https://github.com/JeysonFlores/switcher/issues/14

I have a couple other comments, but these are all non-blocking:

I commented on the background portal, let's follow up on that in a future release. I'm not gonna block you on that since it's not well documented.

There is a new `6.1` release of our Flatpak runtime, so I'd recommend you update from `6` in your manifest before your next release.

Also, you shouldn't need the sandbox hole for `org.freedesktop.Accounts` anymore since we expose the dark style preference over the settings portal

I'm guessing you're using `org.elementary.Contractor` to set wallpapers? That's probably okay for now, but in the future you'll want to switch to using the wallpaper portal for this: https://docs.flatpak.org/en/latest/portal-api-reference.html#gdbus-org.freedesktop.portal.Wallpaper

Also, if you want to monetize your app, you can generate a new Stripe key at https://developer.elementary.io/

**Comment by JeysonFlores** [comment]
Hey, thanks for reviewing my app.

> The only blocking request I have here is for JeysonFlores/switcher#14 

Fixed in[ #15](https://github.com/JeysonFlores/switcher/pull/15)

> There is a new 6.1 release of our Flatpak runtime, so I'd recommend you update from 6 in your manifest before your next release.
> 
> Also, you shouldn't need the sandbox hole for org.freedesktop.Accounts anymore since we expose the dark style preference over the settings portal

Got it, That's settled in [#16](https://github.com/JeysonFlores/switcher/pull/16)


> I commented on the background portal issue on your repo, let's follow up on that in a future release. I'm not gonna block you on that since it's not well documented.

Thanks! I know the importance of using Flatpak Portals so I'll be checking for that documentation and will adapt this app asap.

> I'm guessing you're using org.elementary.Contractor to set wallpapers? 

Yes, I'm using the contractor to do it.

> That's probably okay for now, but in the future you'll want to switch to using the wallpaper portal for this: https://docs.flatpak.org/en/latest/portal-api-reference.html#gdbus-org.freedesktop.portal.Wallpaper

 I see, thanks for the information. Glad it's not a critical sandbox hole, I'll take my time to do it thru the portal but definitely will do it. 

> Also, if you want to monetize your app, you can generate a new Stripe key at https://developer.elementary.io/

Honestly, I'm not really aware about how does the payment process work, and I've recently seen in the slack's appcenter section that a lot of people are having problems on generating stripe keys for new apps. I'll definitely ask int the slack for more information.

**Comment by JeysonFlores** [comment]
Released changed to [1.0.0-3](https://github.com/JeysonFlores/switcher/releases/tag/1.0.0-3)

**Review by danrabbit — APPROVED** [review]
Lookin' good, nice work!

**Pull request merged**
