### PR TITLE
com.github.candiedoperation.ordne 1.0.2

### PR DESCRIPTION
**Pull request by candiedoperation**
- Repository: [candiedoperation/ordne](https://github.com/candiedoperation/ordne)
 - Submitted By: @candiedoperation

### CODE REVIEW

**Comment by candiedoperation** [comment]
@btkostner, Sorry for the mention but, I wanted to know the estimated time for `elementary/app-reviewers` to complete this review...

**Comment by danrabbit** [comment]
Hey thanks for submitting an app here! The submission process isn't strictly open yet as we're still working on it. So it may take a little while to review :)

**Comment by candiedoperation** [comment]
Thank You for the response @danrabbit

**Comment by candiedoperation** [comment]
@btkostner, Sorry for the mention. This pull request has been around here for more than a month. I understand the AppCenter Submission process for Elementary OS 6 is still in development. But, I would like to know the estimated time for the apps to be reviewed and published to AppCenter for Elementary OS 6.

**Comment by btkostner** [comment]
Hey @candiedoperation, right now the team is focusing and putting all effort into getting this repository all setup, the dashboard working, and payments tested. These are the last things needed before we can release an RC build, so I'm sure you can understand how important it is to us. Because of that, nobody on the team can really give an accurate time frame for when this PR will get the attention it needs.

**Comment by cassidyjames** [comment]
@candiedoperation an important question for us to consider: do you intend to monetize Ordne right away? If so, we'll need to wait until we get that step of the AppCenter Dashboard completed. If you would be fine not monetizing it from the start, then we could work to review this sooner.

**Comment by candiedoperation** [comment]
> @candiedoperation an important question for us to consider: do you intend to monetize Ordne right away? If so, we'll need to wait until we get that step of the AppCenter Dashboard completed since this is a new app. If you would be fine not monetizing it from the start, then we could work to review this sooner.

@cassidyjames, I **would not** like to monetize Ordne. I would like to distribute it as a **free app**.

**Review by candiedoperation — COMMENTED** [review]
Updated Commit ID (Incorrectly Entered Earlier)

**Comment by danrabbit** [comment]
@candiedoperation Thanks for your patience while we finish up the 6.0 release and the new AppCenter workflow!

One thing I noticed is that your app is still building against the daily version of the elementary flatpak platform. Before publishing, we'll want to update that to `6` so that your app is using a stable platform

I also noticed that in your manifest you've added libcanberra, but I don't see that you've added `  - '--socket=pulseaudio'` to your finish args. I'm fairly certain that without this your app will not be able to play sounds

**Comment by candiedoperation** [comment]
> @candiedoperation Thanks for your patience while we finish up the 6.0 release and the new AppCenter workflow!
> 
> One thing I noticed is that your app is still building against the daily version of the elementary flatpak platform. Before publishing, we'll want to update that to `6` so that your app is using a stable platform
> 
> I also noticed that in your manifest you've added libcanberra, but I don't see that you've added ` - '--socket=pulseaudio'` to your finish args. I'm fairly certain that without this your app will not be able to play sounds

@danrabbit, I've incorporated the above changes in the repo. Do I need to create a new release and a new pull request here?

**Comment by danrabbit** [comment]
@candiedoperation it looks like according to a comment from a user on your repo, it appears to be working as expected there: https://github.com/candiedoperation/ordne/issues/17#issuecomment-887933908

I'd be happy to re-review once a new release is tagged

**Comment by candiedoperation** [comment]
> @candiedoperation it looks like according to a comment from a user on your repo, it appears to be working as expected there: [candiedoperation/ordne#17 (comment)](https://github.com/candiedoperation/ordne/issues/17#issuecomment-887933908)
> 
> I'd be happy to re-review once a new release is tagged

Hello @danrabbit, I've created a new release incorporating all requested changes as Ordne 1.0.2 and updated this pull request itself

**Comment by danrabbit** [comment]
Looks good!

**Pull request merged**
