### PR TITLE
com.github.alecaddd.sequeler 0.8.1

### PR DESCRIPTION
**Pull request by danrabbit**
- Repository: [alecaddd/sequeler](https://github.com/alecaddd/sequeler)
 - Submitted By: @alecaddd

### CODE REVIEW

**Comment by danrabbit** [comment]
- [ ] Runtime version needs to be updated to `6`
- [ ] Screenshots need to be updated
- [ ] Stripe key is missing https://github.com/Alecaddd/sequeler/issues/364

**Comment by Alecaddd** [comment]
Thanks for the checklist

**Comment by Alecaddd** [comment]
Updated all the things: https://github.com/Alecaddd/sequeler/releases/tag/v0.8.2

**Comment by danrabbit** [comment]
Looks good! nice work :)

**Pull request merged**
