### PR TITLE
com.github.suzie97.communique 1.0.0

### PR DESCRIPTION
**Pull request by danrabbit**
Repository: [Suzie97/Communique](https://github.com/Suzie97/Communique)
Submitted By: @Suzie97

## Review Checklist

- [x] App opens
- [x] Does what it says

### AppData
- [x] Name is unique and non-confusing
- [x] Matches description
- [x] Matches screenshot
- [x] Launchable tag with matching ID
- [x] Release tag with matching version and YYYY-MM-DD date
- [x] Custom colors meet WCAG A contrast or greater
- [x] OARS info matches

### Flatpak
- [x] Uses elementary runtime
- [x] Sandbox permissions are reasonable

### CODE REVIEW

**Comment by danrabbit** [comment]
It looks like this is failing to build because it's not finding the manifest which is [a few directories deep](https://github.com/Suzie97/Communique/blob/master/build-aux/flatpak/com.github.suzie97.communique.yml). @btkostner should we advise the developer to move this up higher in the tree?

**Comment by btkostner** [comment]
Yes we should

**Comment by Suzie97** [comment]
Do I need to make another release or just commit the changes to master?

**Comment by btkostner** [comment]
You'll need to make another release and then this PR will need to be updated with that release info.

**Comment by Suzie97** [comment]
I made a release with the changes. The PR can now be updated.

**Comment by danrabbit** [comment]
@Suzie97 it looks like we're now failing to build due to some invalid `ul` tags in AppData: https://github.com/elementary/appcenter-reviews/pull/112/checks?check_run_id=3548247847

**Comment by Suzie97** [comment]
@danrabbit I had missed a '/'. :( I released it now.

**Comment by danrabbit** [comment]
@Suzie97 can you explain why your app needs some of these finish args here? Particularly I'm looking at:

These dconf lines. Gsettings will automatically switch to storing settings in a keyfile when in a sandbox
```
  - '--filesystem=xdg-run/dconf'
  - '--filesystem=~/.config/dconf:ro'
  - '--talk-name=ca.desrt.conf'
  - '--env=DCONF_USER_CONFIG_DIR=.config/dconf'
```

If you want to migrate settings from a previous local install, you can use a line like:

```
  - '--metadata=X-DConf=migrate-path=/com/github/suzie97/communique/'
```

I'm also wondering about this access to secrets?

and also access to ` io.elementary.AccountsService`

**Comment by Suzie97** [comment]
> @Suzie97 can you explain why your app needs some of these finish args here? Particularly I'm looking at:
> 
> These dconf lines. Gsettings will automatically switch to storing settings in a keyfile when in a sandbox
> 
> ```
>   - '--filesystem=xdg-run/dconf'
>   - '--filesystem=~/.config/dconf:ro'
>   - '--talk-name=ca.desrt.conf'
>   - '--env=DCONF_USER_CONFIG_DIR=.config/dconf'
> ```
> 
> If you want to migrate settings from a previous local install, you can use a line like:
> 
> ```
>   - '--metadata=X-DConf=migrate-path=/com/github/suzie97/communique/'
> ```
> 
> I'm also wondering about this access to secrets?
> 
> and also access to ` io.elementary.AccountsService`

Thanks for the insight. Access to secrets was required for the online syncing services to work. `io.elementary.AccountsService` was a careless mistake. Very sorry for that. 

And I can use this  `- '--metadata=X-DConf=migrate-path=/com/github/suzie97/communique/'`. Thanks a lot!

**Comment by Suzie97** [comment]
I implemented the permission changes.

**Comment by danrabbit** [comment]
That latest release seems to do the trick. Nice work!

**Pull request merged**
