### PR TITLE
com.github.bluesabre.darkbar 0.1.2

### PR DESCRIPTION
**Pull request by danrabbit**
- Repository: [bluesabre/darkbar](https://github.com/bluesabre/darkbar)
 - Submitted By: @bluesabre

### CODE REVIEW

**Comment by danrabbit** [comment]
@bluesabre I'm wondering where this stripe key is from? I don't see a previous release of Darkbar in AppCenter. These keys are specific to both AppCenter and the app, so a key associated with another app or your public key from your Stripe dashboard won't work here

**Comment by bluesabre** [comment]
@danrabbit When I attempted to connect to Stripe from the AppCenter dashboard, it created this key. I'd be happy to generate a new one, please point me in the right direction. :)

**Comment by danrabbit** [comment]
@bluesabre ah okay. Might work then! Worth a try :)

**Comment by bluesabre** [comment]
@danrabbit I tested out payment on AppCenter and it failed, possibly related to the stripe key. The debug message shows:

```
** (io.elementary.appcenter:4738): DEBUG: 08:38:01.213: StripeDialog.vala:415: Houston data:{"errors":[{"status":400,"title":"com.github.bluesabre.darkbar project does not have payments enabled","detail":null,"source":{"parameter":"project","pointer":null}}],"meta":{"date":"2021-08-10T08:38:01.181Z","version":"0.4.1","environment":"production","commit":"e130744a726a8b074545783572b9c9b1826b1825"},"links":{"self":"http://developer.elementary.io/api/payment/com.github.bluesabre.darkbar"},"jsonapi":{"version":"1.0"}}
```

Please let me know if there's any other details I can provide.

**Comment by btkostner** [comment]
Hello, I just wanted to drop by and say that the Stripe token integration for the new AppCenter dashboard is live. You can now go to https://beta.developer.elementary.io/ and type your app URL in. There you will see a "Get a Stripe key" link to log in with Stripe. After you complete your on-boarding you will see the needed Stripe token. Let me know if you have any questions.

**Pull request merged**
