### PR TITLE
com.github.treagod.spectator 0.6.2

### PR DESCRIPTION
**Pull request by danrabbit**
Repository: [treagod/spectator](https://github.com/treagod/spectator)
Submitted By: @treagod

## Review Checklist

- [x] App opens
- [x] Does what it says
- [x] Categories match

### AppData
- [x] https://github.com/treagod/spectator/issues/82
- [x] Name is unique and non-confusing
- [x] Matches description
- [x] https://github.com/treagod/spectator/issues/81
- [x] https://github.com/treagod/spectator/issues/83
- [x] Release tag with matching version and YYYY-MM-DD date
- [x] OARS info matches

### Flatpak
- [x] Uses elementary runtime
- [x] Sandbox permissions are reasonable

### CODE REVIEW

**Comment by danrabbit** [comment]
@treagod Thanks for this update!

Filed an issue report about a blocker here: https://github.com/treagod/spectator/issues/82

A couple of other non-blocking comments:

There's a new elementary OS runtime `6.1` available, so we highly recommend updating from `6` in your manifest for your next release.

The sandbox hole for `accountsservice` is no longer required for the dark style preference. We use the settings portal for that now, so that can be dropped from your manifest

You might want to consider some additional Desktop Entry categories from [this list](https://specifications.freedesktop.org/menu-spec/latest/apas02.html). At least probably `WebDevelopment` could fit here but maybe more

**Comment by treagod** [comment]
I think I've fixed everything. Why is the list-item `Matches screenshot` unchecked?

**Comment by danrabbit** [comment]
Hey @treagod thanks for updating!

It looks like your appdata is pointing to screenshots in the branch `master`, but your updated screenshots were pushed to `main`, so you'll need just one more little point release :sweat_smile:

**Comment by danrabbit** [comment]
Everything looks good, nice work! :tada:

**Pull request merged**
