### PR TITLE
com.github.phase1geo.minder 1.13.0

### PR DESCRIPTION
**Pull request by danrabbit**
- Repository: [phase1geo/minder](https://github.com/phase1geo/minder)
 - Submitted By: @phase1geo

## Review Checklist

- [x] App opens
- [x] Does what it says
- [x] Matches description in AppData
- [x] Matches screenshot
- [x] AppData custom colors are contrasty
- [x] Name is unique and non-confusing
- [x] Uses elementary Flatpak runtime

### CODE REVIEW

**Comment by danrabbit** [comment]
@phase1geo it looks like your screenshots need to be updated :)

**Comment by danrabbit** [comment]
Looks like screenshots were updated, just needs a new release

**Comment by phase1geo** [comment]
1.13.1 has been released now.

**Comment by danrabbit** [comment]
Looking great! Nice update :)

**Pull request merged**
