### PR TITLE
Update Detective to 1.1.0

### PR DESCRIPTION
**Pull request by leolost2605**
Release notes: https://github.com/leolost2605/detective/releases/tag/1.1.0

## Review Checklist

- [ ] App opens
- [ ] Does what it says
- [ ] Categories match

### AppData
- [ ] Name is unique and non-confusing
- [ ] Matches description
- [ ] Matches screenshot
- [ ] Launchable tag with matching ID
- [ ] Release tag with matching version and YYYY-MM-DD date
- [ ] Custom colors meet WCAG A contrast or greater
- [ ] OARS info matches

### Flatpak
- [ ] Uses elementary runtime
- [ ] Sandbox permissions are reasonable

### CODE REVIEW

**Review by danirabbit — CHANGES_REQUESTED** [review]
I think we probably explicitly don't want third party apps to be able to access Gala's desktop integration features as a matter of security. Especially not without like explicit consent. Apps not being able to focus themselves or see other running apps or windows on Wayland is a feature

**Comment by leolost2605** [comment]
I kinda disagree but I updated it :)

**Comment by danirabbit** [comment]
It looks like it's still touching gala here? https://github.com/leolost2605/detective/compare/1.0.2...08a375610aad69458cfd0e085f517fa6212c41af

Accessing this interface without explicit user consent is a pretty serious privacy issue imo. If apps want to be able to read this kind of information, it needs to be through a portion where users can say no

**Comment by leolost2605** [comment]
I'm not sure whether I missed something but the main part (i.e. DesktopIntegration.vala and the stuff that uses it) can (and is in the AppCenter version) be disabled via a meson build option, so that it's not even compiled in.

**Comment by danirabbit** [comment]
Ah sorry I didn't catch that there was a meson flag there. Will re-review Monday!

**Review by danirabbit — APPROVED** [review]

**Pull request merged**
