### PR TITLE
com.github.ryonakano.louper 2.0.0

### PR DESCRIPTION
**Pull request by ryonakano**
Commit history: https://github.com/ryonakano/louper/compare/1.0.2...2.0.0

### CODE REVIEW

**Review by danirabbit — CHANGES_REQUESTED** [review]
Hey congrats on porting to Gtk4!

It looks like you're subclassing Adw.Application which forces the Adwaita stylesheet, but you need to use the elementary stylesheet to publish in AppCenter, so you'll have to subclass Gtk.Application instead

**Comment by ryonakano** [comment]
Ah, I didn't know that, I'll fix and release the new version 2.0.1.

However, it looks like replacing `Adw.Application` with `Gtk.Application` didn't give us the elemenary-styled app window:

```diff
-public class Application : Adw.Application {
+public class Application : Gtk.Application {
```

2022-12-28 19 55 50 のスクリーンショット

**Comment by ryonakano** [comment]
Hmm, maybe I shouldn't switch from granite to libadwaita? 

https://github.com/ryonakano/louper/commit/de83235a2f69ea164e21f4ead9a82e944c4f2295

**Comment by ryonakano** [comment]
The following changes throw away libadwaita style, but I'm not sure why the headerbar style not get the "flat" style applied.

2022-12-28 20 08 31 のスクリーンショット

```diff
diff --git a/src/Application.vala b/src/Application.vala
index 717a585..6224e46 100644
--- a/src/Application.vala
+++ b/src/Application.vala
@@ -3,7 +3,7 @@
  * SPDX-FileCopyrightText: 2021-2023 Ryo Nakano <ryonakaknock3@gmail.com>
  */
 
-public class Application : Adw.Application {
+public class Application : Gtk.Application {
     public static bool no_close_on_unfocus = false;
     public static string text = "";
 
@@ -42,9 +42,6 @@ public class Application : Adw.Application {
             return;
         }
 
-        var style_manager = Adw.StyleManager.get_default ();
-        style_manager.color_scheme = Adw.ColorScheme.PREFER_LIGHT;
-
         window = new MainWindow ();
         window.set_application (this);
         window.present ();
```

**Comment by ryonakano** [comment]
Hi @danirabbit I replaced libadwaita with granite so I guess now the app should meet the publishing requirements to AppCenter :pray:

**Review by danirabbit — APPROVED** [review]
Perfect, perfect! Nice work. Looks great. Congrats on the Gtk4 port :tada:

**Pull request merged**
