### PR TITLE
com.github.hezral.stashed.json 1.0.0

### PR DESCRIPTION
**Pull request by hezral**
Repository: [hezral/stashed](https://github.com/hezral/stashed)
Submitted By: @hezral 

## Review Checklist

- [x] App opens
- [x] Does what it says

### AppData
- [x] Name is unique and non-confusing
- [x] Matches description
- [x] Matches screenshot
- [x] https://github.com/hezral/stashed/issues/5
- [x] Release tag with matching version and YYYY-MM-DD date
- [x] https://github.com/hezral/stashed/issues/6
- [x] OARS info matches

### Flatpak
- [x] Uses elementary runtime
- [x] Sandbox permissions are reasonable
- [x] https://github.com/hezral/stashed/issues/7

### CODE REVIEW

**Comment by danrabbit** [comment]
Hey @hezral I think we're just waiting on a new release here with the appdata fix :)

**Comment by hezral** [comment]
Hey @danrabbit, i created https://github.com/hezral/stashed/releases/tag/1.0.1 and also updated the manifest to remove the `appstream-compose = false` which was causing the issue where the app name isn't recognized.

**Review by danrabbit — CHANGES_REQUESTED** [review]
Filed a few issues with requested changes :)

**Comment by danrabbit** [comment]
@hezral looks like we just need that 1.0.2 release tag and we can get this published :)

**Comment by hezral** [comment]
thanks @danrabbit! https://github.com/hezral/stashed/releases/tag/1.0.2 released 😄

**Review by danrabbit — APPROVED** [review]
Everything looks good, nice work!

**Comment by hezral** [comment]
thanks for the guidance!

**Pull request merged**
