### PR TITLE
com.github.skarva.lockbox 1.3.1

### PR DESCRIPTION
**Pull request by danrabbit**
https://github.com/skarva/lockbox

## Review Checklist

- [x] App opens
- [x] Does what it says
- [ ] Categories match

### AppData
- [x] Name is unique and non-confusing
- [x] Matches description
- [x] https://github.com/skarva/lockbox/issues/26
- [x] Matches screenshot
- [x] Launchable tag with matching ID
- [x] https://github.com/skarva/lockbox/issues/27
- [x] Release tag with matching version and YYYY-MM-DD date
- [x] Custom colors meet WCAG A contrast or greater
- [x] OARS info matches

### Flatpak
- [x] Uses elementary runtime
- [x] Sandbox permissions are reasonable

### CODE REVIEW

**Comment by danrabbit** [comment]
Hey @zeebok! Filed a couple of issue reports about things missing to be published. Couple of other non-blocking comments:

You only need to include tags in OARS when the value isn't `none`. If you don't have any content warnings to disclose, you can self close the OARS tag like: `<content_rating type="oars-1.1" />`

I noticed there's a suggested price in appdata, but no stripe key. If you'd like to monetize, you can generate a new stripe key at https://developer.elementary.io and include that in appdata in a `x-appcenter-stripe` custom tag

**Comment by zeebok** [comment]
Just made a new that addresses everything

**Comment by zeebok** [comment]
Oh I didn't notice the "Categories match" item. Is that in reference to the desktop file? I just went off of what the metainfo creator recommended and generated.

**Comment by danrabbit** [comment]
@zeebok Gonna review the changes now!

Regarding categories, yes that's with the desktop file. I would recommend adding `Security` from https://specifications.freedesktop.org/menu-spec/latest/apas02.html. We're considering removing the `Utility` category from the homepage in future versions of AppCenter since it ends up as kind of a junk drawer

**Comment by danrabbit** [comment]
Update looks good! In the next release please match the exact version from your appdata and git tags. So `1.3.1` to `1.3.1`, not `1.3`

**Pull request merged**
